Gravity Model to test if being a BRI-member country makes a difference in trade

In [ ]:
 # Import packages
import numpy as np
import matplotlib.pyplot as plt
import sklearn
import sklearn.datasets
import sklearn.linear_model
from sklearn import preprocessing
import pandas as pd

%matplotlib inline

np.random.seed(1)

In [ ]:
# Here we imported our data from our Google drive. You may need to import data in another way.
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
path = "/content/drive/My Drive/Colab Notebooks/Data/data_in_excel.csv"
df_raw = pd.read_csv(path)

In [ ]:
# In the next lines, we formatted the data. This way our CSV data is easy to read
df_raw.head()

country  year      china_gdp  ...      imp        exp      total
0  Afghanistan  2008  4594306848763  ...  2693017  151626761  154319778
1  Afghanistan  2009  5101702432883  ...  1375868  213366201  214742069
2  Afghanistan  2010  6087164527421  ...  3680419  175264609  178945028
3  Afghanistan  2011  7551500425598  ...  4403087  230009966  234413053
4  Afghanistan  2012  8532230724142  ...  5186565  464033546  469220111

[5 rows x 10 columns]

In [ ]:
df_raw.shape

(825, 10)

In [ ]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 825 entries, 0 to 824
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   country    825 non-null    object
 1   year       825 non-null    int64 
 2   china_gdp  825 non-null    int64 
 3   gdp        825 non-null    int64 
 4   dist       825 non-null    int64 
 5   border     825 non-null    int64 
 6   bri        825 non-null    int64 
 7   imp        825 non-null    int64 
 8   exp        825 non-null    int64 
 9   total      825 non-null    int64 
dtypes: int64(9), object(1)
memory usage: 64.6+ KB


In [ ]:
# Normalization of data happens here
df_raw["imp"] = (df_raw["imp"]-df_raw["imp"].mean())/df_raw["imp"].std()
df_raw["exp"] = (df_raw["exp"]-df_raw["exp"].mean())/df_raw["exp"].std()
df_raw["china_gdp"] = (df_raw["china_gdp"]-df_raw["china_gdp"].mean())/df_raw["china_gdp"].std()
df_raw["total"] = (df_raw["total"]-df_raw["total"].mean())/df_raw["total"].std()
df_raw["gdp"] = (df_raw["gdp"]-df_raw["gdp"].mean())/df_raw["gdp"].std()
df_raw["dist"] = (df_raw["dist"]-df_raw["dist"].mean())/df_raw["dist"].std()

In [ ]:
df_raw.head()

country  year  china_gdp       gdp  ...  bri       imp       exp     total
0  Afghanistan  2008  -1.586325 -0.496193  ...    0 -0.511530 -0.593190 -0.588332
1  Afghanistan  2009  -1.406528 -0.490391  ...    0 -0.511647 -0.588314 -0.585652
2  Afghanistan  2010  -1.057328 -0.481882  ...    0 -0.511442 -0.591323 -0.587239
3  Afghanistan  2011  -0.538437 -0.477032  ...    0 -0.511378 -0.587000 -0.584779
4  Afghanistan  2012  -0.190913 -0.471561  ...    0 -0.511308 -0.568518 -0.574364

[5 rows x 10 columns]

In [ ]:
df_raw.drop('country', axis=1, inplace=True)
df_raw.drop('year', axis=1, inplace=True)

In [ ]:
df_raw.head()

china_gdp       gdp      dist  border  bri       imp       exp     total
0  -1.586325 -0.496193 -0.961834       1    0 -0.511530 -0.593190 -0.588332
1  -1.406528 -0.490391 -0.961834       1    0 -0.511647 -0.588314 -0.585652
2  -1.057328 -0.481882 -0.961834       1    0 -0.511442 -0.591323 -0.587239
3  -0.538437 -0.477032 -0.961834       1    0 -0.511378 -0.587000 -0.584779
4  -0.190913 -0.471561 -0.961834       1    0 -0.511308 -0.568518 -0.574364

In [ ]:
# Dividing data set into BRI-member and non-BRI-member countries
df_bri = df_raw[df_raw['bri'] == 1]
df_nonbri = df_raw[df_raw['bri'] == 0]

In [ ]:
df_nonbri.head()

china_gdp       gdp      dist  border  bri       imp       exp     total
0  -1.586325 -0.496193 -0.961834       1    0 -0.511530 -0.593190 -0.588332
1  -1.406528 -0.490391 -0.961834       1    0 -0.511647 -0.588314 -0.585652
2  -1.057328 -0.481882 -0.961834       1    0 -0.511442 -0.591323 -0.587239
3  -0.538437 -0.477032 -0.961834       1    0 -0.511378 -0.587000 -0.584779
4  -0.190913 -0.471561 -0.961834       1    0 -0.511308 -0.568518 -0.574364

In [ ]:
# Choosing data to use
X_B = df_bri[['china_gdp', 'gdp', 'dist', 'border']]
Y_B = df_bri['total']

In [ ]:
X_NB = df_nonbri[['china_gdp', 'gdp', 'dist', 'border']]
Y_NB = df_nonbri['total']

In [ ]:
Y_NB.shape

(496,)

In [ ]:
# Converting dataframe to numpy arrays
X_B.to_numpy();
Y_B.to_numpy();

In [ ]:
X_NB.to_numpy();
Y_NB.to_numpy();

In [ ]:
# Making sure that data has right shape
yb = Y_B.shape[0]
Y_B = Y_B.values.reshape((yb, 1))

In [ ]:
ynb = Y_NB.shape[0]
Y_NB = Y_NB.values.reshape((ynb, 1))

In [ ]:
xb0 = X_B.shape[0]
xb1 = X_B.shape[1]
X_B = X_B.values.reshape((xb0, xb1))

In [ ]:
xnb0 = X_NB.shape[0]
xnb1 = X_NB.shape[1]
X_NB = X_NB.values.reshape((xnb0, xnb1))

In [ ]:
X_B.shape

(329, 4)

In [ ]:
# This line is to check if the data is in arrays instead of dataframes
# isinstance(X_NB, np.ndarray)

In [ ]:
# We need examples in vertical columns instead of horizantal lines. Therefore, we took transpose
X_B = X_B.T
Y_B = Y_B.T
X_NB = X_NB.T
Y_NB = Y_NB.T


In [ ]:
Y_B.shape

(1, 329)

In [ ]:
def layer_sizes(X, Y):
    """
    Arguments:
    X -- input dataset of shape (input size, number of examples)
    Y -- labels of shape (output size, number of examples)
    
    Returns:
    n_x -- the size of the input layer
    n_h -- the size of the hidden layer
    n_y -- the size of the output layer
    """
    n_x = X.shape[0] # size of input layer
    n_h = 20          # size of the hidden layer
    n_y = Y.shape[0] # size of output layer
    
    return (n_x, n_h, n_y)

In [ ]:
(n_x, n_h, n_y) = layer_sizes(X_B, Y_B)
print("The size of the input layer is: n_x = " + str(n_x))
print("The size of the hidden layer is: n_h = " + str(n_h))
print("The size of the output layer is: n_y = " + str(n_y))

The size of the input layer is: n_x = 4
The size of the hidden layer is: n_h = 20
The size of the output layer is: n_y = 1


In [ ]:
def initialize_parameters(n_x, n_h, n_y):
    """
    Argument:
    n_x -- size of the input layer
    n_h -- size of the hidden layer
    n_y -- size of the output layer
    
    Returns:
    params -- python dictionary containing your parameters:
                    W1 -- weight matrix of shape (n_h, n_x)
                    b1 -- bias vector of shape (n_h, 1)
                    W2 -- weight matrix of shape (n_y, n_h)
                    b2 -- bias vector of shape (n_y, 1)
    """
    
    np.random.seed(2) 
    
    W1 = np.random.randn(n_h, n_x) * 0.01
    b1 = np.zeros((n_h, 1))
    W2 = np.random.randn(n_y, n_h) * 0.01
    b2 = np.zeros((n_y, 1))
    
    assert (W1.shape == (n_h, n_x))
    assert (b1.shape == (n_h, 1))
    assert (W2.shape == (n_y, n_h))
    assert (b2.shape == (n_y, 1))
    
    parameters = {"W1": W1,
                  "b1": b1,
                  "W2": W2,
                  "b2": b2}
    
    return parameters

In [ ]:
parameters = initialize_parameters(n_x, n_h, n_y)
print("W1 = " + str(parameters["W1"]))
print("b1 = " + str(parameters["b1"]))
print("W2 = " + str(parameters["W2"]))
print("b2 = " + str(parameters["b2"]))

W1 = [[-4.16757847e-03 -5.62668272e-04 -2.13619610e-02  1.64027081e-02]
 [-1.79343559e-02 -8.41747366e-03  5.02881417e-03 -1.24528809e-02]
 [-1.05795222e-02 -9.09007615e-03  5.51454045e-03  2.29220801e-02]
 [ 4.15393930e-04 -1.11792545e-02  5.39058321e-03 -5.96159700e-03]
 [-1.91304965e-04  1.17500122e-02 -7.47870949e-03  9.02525097e-05]
 [-8.78107893e-03 -1.56434170e-03  2.56570452e-03 -9.88779049e-03]
 [-3.38821966e-03 -2.36184031e-03 -6.37655012e-03 -1.18761229e-02]
 [-1.42121723e-02 -1.53495196e-03 -2.69056960e-03  2.23136679e-02]
 [-2.43476758e-02  1.12726505e-03  3.70444537e-03  1.35963386e-02]
 [ 5.01857207e-03 -8.44213704e-03  9.76147160e-08  5.42352572e-03]
 [-3.13508197e-03  7.71011738e-03 -1.86809065e-02  1.73118467e-02]
 [ 1.46767801e-02 -3.35677339e-03  6.11340780e-03  4.79705919e-04]
 [-8.29135289e-03  8.77102184e-04  1.00036589e-02 -3.81092518e-03]
 [-3.75669423e-03 -7.44707629e-04  4.33496330e-03  1.27837923e-02]
 [-6.34679305e-03  5.08396243e-03  2.16116006e-03 -1.8586

In [ ]:
def sigmoid(z):
  sig = 1/(1 + np.exp(-z))
  return sig

In [ ]:
def forward_propagation(X, parameters):
    """
    Argument:
    X -- input data of size (n_x, m)
    parameters -- python dictionary containing your parameters (output of initialization function)
    
    Returns:
    A2 -- The sigmoid output of the second activation
    cache -- a dictionary containing "Z1", "A1", "Z2" and "A2"
    """
    # Retrieve each parameter from the dictionary "parameters"
    W1 = parameters["W1"]
    b1 = parameters["b1"]
    W2 = parameters["W2"]
    b2 = parameters["b2"]
    
    # Implement Forward Propagation to calculate A2 (probabilities)
    Z1 = np.dot(W1,X) + b1
    A1 = np.tanh(Z1)              # tanh activation function for the hidden layer
    Z2 = np.dot(W2,A1) + b2
    A2 = np.maximum(Z2, 0.00001)  #We used ReLU activation function for the outer layer
    
    assert(A2.shape == (1, X.shape[1]))
    
    cache = {"Z1": Z1,
             "A1": A1,
             "Z2": Z2,
             "A2": A2}
    
    return A2, cache

In [ ]:
(n_x, n_h, n_y) = layer_sizes(X_B, Y_B)
parameters = initialize_parameters(n_x, n_h, n_y)
(A2, cache) = forward_propagation(X_B, parameters)

In [ ]:
A2 = cache["A2"]
A1 = cache["A1"]
Z2 = cache["Z2"]
# Lines below are redundant code I used to check I'm doing it right or to debug the code
#np.array(A2) < 0
#A2.shape
#print(Z2[0, 74:80])
#print(A3[0, 20:23])
#np.amin(A2)

In [ ]:
A2, cache = forward_propagation(X_B, parameters)

print(np.mean(cache['Z1']) ,np.mean(cache['A1']),np.mean(cache['Z2']),np.mean(cache['A2']))

-0.005537674997878948 -0.005536259995527388 0.0008220633506687536 0.0008506774237981132


In [ ]:
def compute_cost(A2, Y, parameters):
    """
    Computes the cross-entropy cost given in equation (13)
    
    Arguments:
    A2 -- The sigmoid output of the second activation, of shape (1, number of examples)
    Y -- "true" labels vector of shape (1, number of examples)
    parameters -- python dictionary containing your parameters W1, b1, W2 and b2
    
    Returns:
    cost -- MSE
    
    """
    W1 =parameters["W1"]
    W2 =parameters["W2"]

    m = Y.shape[1] # number of example

    # Compute the MSE cost
    MSE = np.square(A2 - Y)
    #logprobs = np.multiply(np.log(A2),Y) + np.multiply(np.log(1-A2),1-Y)
    cost = np.sum(MSE) * (1/m)
    
    cost = float(np.squeeze(cost))  # makes sure cost is the dimension we expect. 
                                    # E.g., turns [[17]] into 17 
    assert(isinstance(cost, float))
    
    return cost

In [ ]:
print("cost = " + str(compute_cost(A2, Y_B, parameters)))

cost = 1.4608018387936497


In [ ]:
def backward_propagation(parameters, cache, X, Y):
    """
    Implement the backward propagation using the instructions above.
    
    Arguments:
    parameters -- python dictionary containing our parameters 
    cache -- a dictionary containing "Z1", "A1", "Z2" and "A2".
    X -- input data of shape (2, number of examples)
    Y -- "true" labels vector of shape (1, number of examples)
    
    Returns:
    grads -- python dictionary containing gradients with respect to different parameters
    """
    m = X.shape[1]
    
    # First, retrieve W1 and W2 from the dictionary "parameters".
    W1 = parameters["W1"]
    W2 = parameters["W2"]
        
    # Retrieve also A1 and A2 from dictionary "cache".
    A1 = cache["A1"]
    A2 = cache["A2"]
    
    # Backward propagation: calculate dW1, db1, dW2, db2. 
    dZ2 = 2 * (A2-Y)
    dW2 = (1/m) * np.dot(dZ2,A1.T)
    db2 = (1/m) * np.sum(dZ2, axis = 1, keepdims = True)
    dZ1 = np.dot(W2.T,dZ2) * (1 - np.square(A1))
    dW1 = (1/m) * np.dot(dZ1,X.T)
    db1 = (1/m) * np.sum(dZ1, axis = 1, keepdims = True)
    
    grads = {"dW1": dW1,
             "db1": db1,
             "dW2": dW2,
             "db2": db2}
    
    return grads

In [ ]:
grads = backward_propagation(parameters, cache, X_B, Y_B)
print ("dW1 = "+ str(grads["dW1"]))
print ("db1 = "+ str(grads["db1"]))
print ("dW2 = "+ str(grads["dW2"]))
print ("db2 = "+ str(grads["db2"]))

dW1 = [[ 0.00069181  0.00304542 -0.00137809  0.00042949]
 [ 0.00028089  0.00123758 -0.00056122  0.00017443]
 [-0.00300917 -0.01324905  0.00600162 -0.00187012]
 [-0.00455127 -0.02002722  0.00907956 -0.00282433]
 [ 0.00147269  0.00648058 -0.00293785  0.00091402]
 [ 0.00505643  0.02225614 -0.01007655  0.0031401 ]
 [-0.00499557 -0.02198268  0.00995329 -0.00310211]
 [-0.00445031 -0.01958364  0.00886545 -0.0027641 ]
 [ 0.0016872   0.00742758 -0.00336156  0.00104837]
 [-0.00128186 -0.00563982  0.00255421 -0.00079591]
 [-0.00139189 -0.00612651  0.0027752  -0.00086326]
 [-0.0020701  -0.00910628  0.0041221  -0.00128522]
 [-0.00074584 -0.00328355  0.0014861  -0.00046329]
 [-0.00514075 -0.02262328  0.01024092 -0.00319281]
 [ 0.00635109  0.02794905 -0.01265144  0.00394412]
 [-0.00380376 -0.01673869  0.0075775  -0.00236232]
 [-0.00138982 -0.00611501  0.00276881 -0.0008629 ]
 [ 0.00079193  0.00348617 -0.00157953  0.00049164]
 [-0.00428724 -0.0188671   0.00854041 -0.00266171]
 [ 0.00853309  0.03760828

In [ ]:
def update_parameters(parameters, grads, learning_rate = 1.2):
    """
    Updates parameters using the gradient descent update rule given above
    
    Arguments:
    parameters -- python dictionary containing your parameters 
    grads -- python dictionary containing your gradients 
    
    Returns:
    parameters -- python dictionary containing your updated parameters 
    """
    # Retrieve each parameter from the dictionary "parameters"
    W1 = parameters["W1"]
    b1 = parameters["b1"]
    W2 = parameters["W2"]
    b2 = parameters["b2"]
    
    # Retrieve each gradient from the dictionary "grads"
    dW1 = grads["dW1"]
    db1 = grads["db1"]
    dW2 = grads["dW2"]
    db2 = grads["db2"]
    
    # Update rule for each parameter
    W1 = W1 - learning_rate * dW1
    b1 = b1 - learning_rate * db1
    W2 = W2 - learning_rate * dW2
    b2 = b2 - learning_rate * db2
    
    parameters = {"W1": W1,
                  "b1": b1,
                  "W2": W2,
                  "b2": b2}
    
    return parameters

In [ ]:
parameters = update_parameters(parameters, grads)

print("W1 = " + str(parameters["W1"]))
print("b1 = " + str(parameters["b1"]))
print("W2 = " + str(parameters["W2"]))
print("b2 = " + str(parameters["b2"]))

W1 = [[-0.00499775 -0.00421717 -0.01970826  0.01588732]
 [-0.01827142 -0.00990257  0.00570228 -0.0126622 ]
 [-0.00696852  0.00680878 -0.0016874   0.02516622]
 [ 0.00587692  0.01285341 -0.00550489 -0.0025724 ]
 [-0.00195854  0.00397331 -0.00395329 -0.00100657]
 [-0.0148488  -0.02827171  0.01465756 -0.01365591]
 [ 0.00260646  0.02401737 -0.0183205  -0.0081536 ]
 [-0.0088718   0.02196542 -0.01332912  0.02563059]
 [-0.02637231 -0.00778583  0.00773832  0.01233829]
 [ 0.0065568  -0.00167436 -0.00306495  0.00637861]
 [-0.00146482  0.01506192 -0.02201114  0.01834776]
 [ 0.0171609   0.00757076  0.00116689  0.00202197]
 [-0.00739634  0.00481736  0.00822034 -0.00325498]
 [ 0.00241221  0.02640322 -0.00795414  0.01661517]
 [-0.01396811 -0.0284549   0.01734289 -0.02331907]
 [ 0.00037134  0.01876314 -0.0094887   0.00609482]
 [-0.01873545  0.00780057 -0.01009933 -0.01335891]
 [ 0.00429265  0.0031694  -0.00463707  0.00783459]
 [ 0.00132953  0.02330541 -0.02123589  0.01903892]
 [-0.0368342  -0.04604446 

In [ ]:
def nn_model(X, Y, n_h, num_iterations = 10000, print_cost=False):
    """
    Arguments:
    X -- dataset of shape (2, number of examples)
    Y -- labels of shape (1, number of examples)
    n_h -- size of the hidden layer
    num_iterations -- Number of iterations in gradient descent loop
    print_cost -- if True, print the cost every 1000 iterations
    
    Returns:
    parameters -- parameters learnt by the model. They can then be used to predict.
    """
    
    np.random.seed(3)
    n_x = layer_sizes(X, Y)[0]
    n_y = layer_sizes(X, Y)[2]
    
    # Initialize parameters
    parameters = initialize_parameters(n_x, n_h, n_y)
    
    # Loop (gradient descent)

    for i in range(0, num_iterations):
         
        # Forward propagation. Inputs: "X, parameters". Outputs: "A2, cache".
        A2, cache = forward_propagation(X, parameters)
        
        # Cost function. Inputs: "A2, Y, parameters". Outputs: "cost".
        cost = compute_cost(A2, Y, parameters)
 
        # Backpropagation. Inputs: "parameters, cache, X, Y". Outputs: "grads".
        grads = backward_propagation(parameters, cache, X, Y)
 
        # Gradient descent parameter update. Inputs: "parameters, grads". Outputs: "parameters".
        parameters = update_parameters(parameters, grads, learning_rate = 0.2)
        
        
        # Print the cost every 1000 iterations
        if print_cost and i % 10000 == 0:
            print ("Cost after iteration %i: %f" %(i, cost))

    return parameters

In [ ]:
parameters = nn_model(X_B, Y_B, 20, num_iterations=100000, print_cost=True)
print("W1 = " + str(parameters["W1"]))
print("b1 = " + str(parameters["b1"]))
print("W2 = " + str(parameters["W2"]))
print("b2 = " + str(parameters["b2"]))

Cost after iteration 0: 1.460802
Cost after iteration 10000: 1.202800
Cost after iteration 20000: 1.447231
Cost after iteration 30000: 1.457294
Cost after iteration 40000: 1.455103
Cost after iteration 50000: 1.454507
Cost after iteration 60000: 1.457801
Cost after iteration 70000: 1.458337
Cost after iteration 80000: 1.455509
Cost after iteration 90000: 1.445553
W1 = [[-2.42286318e+00  7.19048137e-01 -1.08599722e+00 -2.41619425e+00]
 [-2.76665024e+01 -2.34867372e+02  5.47402635e+01  5.15224778e+01]
 [-2.71983843e-01 -1.26611410e-01 -2.72088752e+00 -6.59232638e+00]
 [-2.86983645e-01 -1.06094825e-01 -2.83482180e+00 -6.89640637e+00]
 [ 5.08753247e-01  6.38783097e-01 -1.15733953e+00 -4.00976144e+00]
 [-2.76673046e+01 -2.34874015e+02  5.47418222e+01  5.15239113e+01]
 [ 2.76656643e+01  2.34860432e+02 -5.47386349e+01 -5.15209800e+01]
 [ 2.76660351e+01  2.34863502e+02 -5.47393554e+01 -5.15216426e+01]
 [-1.95836407e-01 -6.64136868e-01  1.18018842e+00  3.83957097e+00]
 [-1.58186557e+00 -7.12763

In [ ]:
def predict(parameters, X):
    """
    Using the learned parameters, predicts a class for each example in X
    
    Arguments:
    parameters -- python dictionary containing your parameters 
    X -- input data of size (n_x, m)
    
    Returns
    predictions -- 
    """
    
    A2, cache = forward_propagation(X, parameters)
    predictions = A2
    
    return predictions

In [ ]:
predictions = predict(parameters, X_NB)

bool_array = np.array(predictions-Y_NB) > 0
print(bool_array)

[[ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True  True  True  True  True  True  True  True  True
   True  True False  True  True  True 

In [ ]:
count = np.count_nonzero(bool_array)

In [ ]:
print(count)

454
